#CodeEmailMKT.Domain.Entity.Tag.dcm.yml
CodeEmailMKT\Domain\Entity\Tag:
  type: entity
  repositoryClass: CodeEmailMKT\Infrastructure\Persistence\Doctrine\Repository\TagRepository
  table: tags
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 200
  manyToMany:
    customers:
      targetEntity: CodeEmailMKT\Domain\Entity\Customer
      inversedBy: tags
    campaigns:
      targetEntity: CodeEmailMKT\Domain\Entity\Campaign
      inversedBy: tags